modLoader = "javafml"
loaderVersion = "${neo_version_range}"
license = "GNU GPLv3"

[[mods]]
modId = "itemgator"
version = "${mod_version}"
displayName = "Item Gator"
displayURL = "http://github.com/oitsjustjose/itemgator"
credits = ""
authors = "oitsjustjose"
description = '''A mod that allows you to prevent players from picking up / getting an item until they have a given tag'''

[[dependencies.itemgator]]
modId = "forge"
mandatory = true
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemgator]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
